general:
  # negative is all
  gpus:              -1
  threads:           1
  # size to load in memory at a time (width x height x bands x bit-width x chunk-size^2)
  block_size_mb:     512
  # number of different images to interleave at a time when loading
  interleave_images: 5
  # ratio of tile width and height when loading images
  tile_ratio:        5.0
  cache:
    # default is OS-specific, in Linux, ~/.cache/delta
    dir:              ~
    limit:            8

images:
  type:             tiff
  # preprocess the images when loading (i.e., scaling)
  preprocess:       true
  directory:        ~
  extension:        ~
  file_list:        ~
  files:            ~

labels:
  type:             tiff
  preprocess:       true
  directory:        ~
  extension:        ~
  file_list:        ~
  files:            ~

network:
  chunk_size:      17
  classes:         4

train:
  chunk_stride:    1
  batch_size:      1000
  steps:           ~ # number of batches to train on (or ~ for all)
  epochs:          5
  loss_function:   sparse_categorical_crossentropy
  experiment_name: ~ # used in tracking tools
  validation:
    steps:         1000
    # if true, skips the first steps from the training set to use for validation instead
    from_training: true
    # otherwise uses the first samples from this dataset:
    images:
      type:        tiff
      preprocess:  true
      directory:   ~
      extension:   ~
      file_list:   ~
      files:       ~
    labels:
      type:        tiff
      preprocess:  true
      directory:   ~
      extension:   ~
      file_list:   ~
      files:       ~
 
mlflow:
  # default to ~/.local/share/delta/mlflow
  enabled:        true
  uri:            ~
tensorboard:
  enabled:        true
  # default to ~/.local/share/delta/tensorboard
  dir:            ~
# defauls to None, saves no checkpoints
checkpoint_dir:  ~
